
<div data-bind="scope: 'messages'">
    <!-- ko if: cookieMessages && cookieMessages.length > 0 -->
    <div role="alert" data-bind="" class="messages">
        <!-- ko foreach: { data: cookieMessages, as: 'message' } -->
        <div class="messages-container">
            <div data-bind="attr: {
                class: 'message-' + message.type + ' ' + message.type + ' message',
                'data-ui-id': 'message-' + message.type
            }">
                <div data-bind="html: message.text"></div>
                <span class="close" data-bind="event: { click:  $parent.closeMessage }">x</span>
            </div>
        </div>
        <!-- /ko -->
    </div>
    <!-- /ko -->
    <!-- ko if: messages().messages && messages().messages.length > 0 -->
    <div role="alert" class="messages">
        <!-- ko foreach: { data: messages().messages, as: 'message' } -->
        <div class="messages-container">
            <div data-bind="attr: {
                class: 'message-' + message.type + ' ' + message.type + ' message',
                'data-ui-id': 'message-' + message.type
            }">
                <div data-bind="html: message.text"></div>
                <span class="close" data-bind="event: { click:  $parent.closeMessage }">x</span>
            </div>
        </div>
        <!-- /ko -->
    </div>
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                        "messages": {
                            "component": "Magento_Theme/js/view/messages"
                        }
                    }
                }
            }
    }
</script>
